from function import *
import cv2 
import numpy as np

# 1.a
baboon_img = cv2.imread("baboon.bmp",0)
baboon_10 = add_salt_and_pepper_noise(baboon_img,0.1)
baboon_30 = add_salt_and_pepper_noise(baboon_img,0.3)
baboon_50 = add_salt_and_pepper_noise(baboon_img,0.5)
baboon_70 = add_salt_and_pepper_noise(baboon_img,0.7)
baboon_90 = add_salt_and_pepper_noise(baboon_img,0.9)
peppers_img = cv2.imread("peppers.bmp",0)
peppers_10 = add_salt_and_pepper_noise(peppers_img,0.1)
peppers_30 = add_salt_and_pepper_noise(peppers_img,0.3)
peppers_50 = add_salt_and_pepper_noise(peppers_img,0.5)
peppers_70 = add_salt_and_pepper_noise(peppers_img,0.7)
peppers_90 = add_salt_and_pepper_noise(peppers_img,0.9)
cv2.imshow("baboon 10%",baboon_10)
cv2.imshow("baboon 30%",baboon_30)
cv2.imshow("baboon 50%",baboon_50)
cv2.imshow("baboon 70%",baboon_70)
cv2.imshow("baboon 90%",baboon_90)
cv2.imshow("peppers 10%",peppers_10)
cv2.imshow("peppers 30%",peppers_30)
cv2.imshow("peppers 50%",peppers_50)
cv2.imshow("peppers 70%",peppers_70)
cv2.imshow("peppers 90%",peppers_90)
# 1.b
print("mean filtering")
print("before denoise")
print("baboon 10%",cv2.PSNR(baboon_10,baboon_img))
print("baboon 30%",cv2.PSNR(baboon_30,baboon_img))
print("baboon 50%",cv2.PSNR(baboon_50,baboon_img))
print("baboon 70%",cv2.PSNR(baboon_70,baboon_img))
print("baboon 90%",cv2.PSNR(baboon_90,baboon_img))
print("peppers 10%",cv2.PSNR(peppers_10,peppers_img))
print("peppers 30%",cv2.PSNR(peppers_30,peppers_img))
print("peppers 50%",cv2.PSNR(peppers_50,peppers_img))
print("peppers 70%",cv2.PSNR(peppers_70,peppers_img))
print("peppers 90%",cv2.PSNR(peppers_90,peppers_img))
print("after denosise")
baboon_10_mean = mean_filter(baboon_10,5)
baboon_30_mean = mean_filter(baboon_30,5)
baboon_50_mean = mean_filter(baboon_50,5)
baboon_70_mean = mean_filter(baboon_70,5)
baboon_90_mean = mean_filter(baboon_90,5)
peppers_10_mean = mean_filter(peppers_10,5)
peppers_30_mean = mean_filter(peppers_30,5)
peppers_50_mean = mean_filter(peppers_50,5)
peppers_70_mean = mean_filter(peppers_70,5)
peppers_90_mean = mean_filter(peppers_90,5)
print("baboon 10%",cv2.PSNR(baboon_10_mean,baboon_img))
print("baboon 30%",cv2.PSNR(baboon_30_mean,baboon_img))
print("baboon 50%",cv2.PSNR(baboon_50_mean,baboon_img))
print("baboon 70%",cv2.PSNR(baboon_70_mean,baboon_img))
print("baboon 90%",cv2.PSNR(baboon_90_mean,baboon_img))
print("peppers 10%",cv2.PSNR(peppers_10_mean,peppers_img))
print("peppers 30%",cv2.PSNR(peppers_30_mean,peppers_img))
print("peppers 50%",cv2.PSNR(peppers_50_mean,peppers_img))
print("peppers 70%",cv2.PSNR(peppers_70_mean,peppers_img))
print("peppers 90%",cv2.PSNR(peppers_90_mean,peppers_img))
# 1.c
print("Gaussian filtering")
print("before denoise")
print("baboon 10%",cv2.PSNR(baboon_10,baboon_img))
print("baboon 30%",cv2.PSNR(baboon_30,baboon_img))
print("baboon 50%",cv2.PSNR(baboon_50,baboon_img))
print("baboon 70%",cv2.PSNR(baboon_70,baboon_img))
print("baboon 90%",cv2.PSNR(baboon_90,baboon_img))
print("peppers 10%",cv2.PSNR(peppers_10,peppers_img))
print("peppers 30%",cv2.PSNR(peppers_30,peppers_img))
print("peppers 50%",cv2.PSNR(peppers_50,peppers_img))
print("peppers 70%",cv2.PSNR(peppers_70,peppers_img))
print("peppers 90%",cv2.PSNR(peppers_90,peppers_img))
print("after denosise")
baboon_10_gaussian = cv2.GaussianBlur(baboon_10, (5,5), 2)
baboon_30_gaussian = cv2.GaussianBlur(baboon_30, (5,5), 2)
baboon_50_gaussian = cv2.GaussianBlur(baboon_50, (5,5), 2)
baboon_70_gaussian = cv2.GaussianBlur(baboon_70, (5,5), 2)
baboon_90_gaussian = cv2.GaussianBlur(baboon_90, (5,5), 2)
peppers_10_gaussian = cv2.GaussianBlur(peppers_10, (5,5), 2)
peppers_30_gaussian = cv2.GaussianBlur(peppers_30, (5,5), 2)
peppers_50_gaussian = cv2.GaussianBlur(peppers_50, (5,5), 2)
peppers_70_gaussian = cv2.GaussianBlur(peppers_70, (5,5), 2)
peppers_90_gaussian = cv2.GaussianBlur(peppers_90, (5,5), 2)
print("baboon 10%",cv2.PSNR(baboon_10_gaussian,baboon_img))
print("baboon 30%",cv2.PSNR(baboon_30_gaussian,baboon_img))
print("baboon 50%",cv2.PSNR(baboon_50_gaussian,baboon_img))
print("baboon 70%",cv2.PSNR(baboon_70_gaussian,baboon_img))
print("baboon 90%",cv2.PSNR(baboon_90_gaussian,baboon_img))
print("peppers 10%",cv2.PSNR(peppers_10_gaussian,peppers_img))
print("peppers 30%",cv2.PSNR(peppers_30_gaussian,peppers_img))
print("peppers 50%",cv2.PSNR(peppers_50_gaussian,peppers_img))
print("peppers 70%",cv2.PSNR(peppers_70_gaussian,peppers_img))
print("peppers 90%",cv2.PSNR(peppers_90_gaussian,peppers_img))
# 1.d
print("Adaptive median filtering")
print("before denoise")
print("baboon 10%",cv2.PSNR(baboon_10,baboon_img))
print("baboon 30%",cv2.PSNR(baboon_30,baboon_img))
print("baboon 50%",cv2.PSNR(baboon_50,baboon_img))
print("baboon 70%",cv2.PSNR(baboon_70,baboon_img))
print("baboon 90%",cv2.PSNR(baboon_90,baboon_img))
print("peppers 10%",cv2.PSNR(peppers_10,peppers_img))
print("peppers 30%",cv2.PSNR(peppers_30,peppers_img))
print("peppers 50%",cv2.PSNR(peppers_50,peppers_img))
print("peppers 70%",cv2.PSNR(peppers_70,peppers_img))
print("peppers 90%",cv2.PSNR(peppers_90,peppers_img))
print("after denoise")
baboon_10_median = adaptive_median_filter(baboon_10)
baboon_30_median = adaptive_median_filter(baboon_30)
baboon_50_median = adaptive_median_filter(baboon_50)
baboon_70_median = adaptive_median_filter(baboon_70)
baboon_90_median = adaptive_median_filter(baboon_90)
peppers_10_median = adaptive_median_filter(peppers_10)
peppers_30_median = adaptive_median_filter(peppers_30)
peppers_50_median = adaptive_median_filter(peppers_50)
peppers_70_median = adaptive_median_filter(peppers_70)
peppers_90_median = adaptive_median_filter(peppers_90)
print("baboon 10%",cv2.PSNR(baboon_10_median,baboon_img))
print("baboon 30%",cv2.PSNR(baboon_30_median,baboon_img))
print("baboon 50%",cv2.PSNR(baboon_50_median,baboon_img))
print("baboon 70%",cv2.PSNR(baboon_70_median,baboon_img))
print("baboon 90%",cv2.PSNR(baboon_90_median,baboon_img))
print("peppers 10%",cv2.PSNR(peppers_10_median,peppers_img))
print("peppers 30%",cv2.PSNR(peppers_30_median,peppers_img))
print("peppers 50%",cv2.PSNR(peppers_50_median,peppers_img))
print("peppers 70%",cv2.PSNR(peppers_70_median,peppers_img))
print("peppers 90%",cv2.PSNR(peppers_90_median,peppers_img))
# 2.a
peppers_004 = cv2.imread('peppers_0.04.bmp', 0)
peppers_sobel = sobel_edge_detection(peppers_img)
peppers_004_sobel = sobel_edge_detection(peppers_004)
cv2.imshow('peppers_sobel',peppers_sobel)
cv2.imshow('peppers_004_sobel',peppers_004_sobel)
# 2.b
peppers_gaussian = cv2.GaussianBlur(peppers_img,(5,5),1)
peppers_004_gaussian = cv2.GaussianBlur(peppers_004,(5,5),1)
peppers_sobel_b = sobel_edge_detection(peppers_gaussian)
peppers_004_sobel_b = sobel_edge_detection(peppers_004_gaussian)
peppers_sobel_b = cv2.Laplacian(peppers_sobel_b, cv2.CV_64F)
peppers_004_sobel_b = cv2.Laplacian(peppers_004_sobel_b,cv2.CV_64F)
cv2.imshow('peppers_sobel_b',peppers_sobel_b)
cv2.imshow('peppers_004_sobel_b',peppers_004_sobel_b)
cv2.waitKey(0)